# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker Compose action
      #   uses: hoverkraft-tech/compose-action@v2.0.0
      #   with:
      #     # Description: Relative path to compose file(s). It can be a list of files.
      #     #
      #     # Default: ./docker-compose.yml
      #     # compose-file: ""

      #     # Description: Services to perform docker-compose up.
      #     #
      #     # services: ""

      #     # Description: Additional options to pass to `docker-compose up` command.
      #     #
      #     # Default:
      #     up-flags: "--build --wait"

      #     # Description: Additional options to pass to `docker-compose down` command.
      #     #
      #     # Default:
      #     # down-flags: ""

      #     # Description: Additional options to pass to `docker-compose` command.
      #     #
      #     # Default:
      #     # compose-flags: ""

      #     # Description: Current working directory
      #     #
      #     # Default: ${{ github.workspace }}
      #     # cwd: ""
      # - name: Tag image with commit SHA and push
      #   run: |
      #     COMMIT_SHA=$(git rev-parse --short HEAD)
      #     docker tag test-actions natefirewall/test-actions:$COMMIT_SHA
      #     docker push natefirewall/test-actions:$COMMIT_SHA
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     profile: minimal
      #     toolchain: stable
      #     override: true
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: run
      #     args: -- test-actions-myservice-1
      - name: Update testnet
        # only publish image if push to main branch
        # if: github.event_name == 'push'
        run: |
          echo ${{ vars.TESTNET_URL }}

          # SECURITY: trust host
          echo  "Host *"  >> ~/.ssh/config
          echo  "  StrictHostKeyChecking=no"  >> ~/.ssh/config
          echo  "  UserKnownHostsFile=/dev/null"  >> ~/.ssh/config

          docker context create \
            --docker host=${{ vars.TESTNET_URL }} \
            --description="Test-infra remote engine" \
            test-infra-remote-engine
          docker context use test-infra-remote-engine
          docker compose up -d